/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.BorderLayout;
import java.util.HashMap;
import java.util.Map;
import volvis.RaycastRenderer;
import volvis.RenderingController;

/**
 *
 * @author michel
 */
public class OpacityWeightPanel extends javax.swing.JPanel {
    
    private final static Map<String,Integer> SELECTION_MAP = new HashMap<String,Integer>();
    static{
        SELECTION_MAP.put("MIP", RaycastRenderer.MIP);
        SELECTION_MAP.put("Compositing", RaycastRenderer.COMPOSITING);
        SELECTION_MAP.put("Opacity weighting", RaycastRenderer.OPACITYWEIGHTING);
    }

    RenderingController renderController;
    OpacityWeightEditor owEditor;
    
    /**
     * Creates new form RaycastRendererPanel
     */
    public OpacityWeightPanel(RenderingController renderer) {
        initComponents();
        this.renderController = renderer;
        this.owPanel.setLayout(new BorderLayout());
    }
    
    public void setOpacityWeightEditor(OpacityWeightEditor ed) {
        if (owEditor != null) {
            owPanel.remove(owEditor);
        }
        owEditor = ed;
        owPanel.add(ed, BorderLayout.CENTER);
        owPanel.repaint();
        repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        owPanel = new javax.swing.JPanel();

        javax.swing.GroupLayout owPanelLayout = new javax.swing.GroupLayout(owPanel);
        owPanel.setLayout(owPanelLayout);
        owPanelLayout.setHorizontalGroup(
            owPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 489, Short.MAX_VALUE)
        );
        owPanelLayout.setVerticalGroup(
            owPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 362, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(owPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(owPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel owPanel;
    // End of variables declaration//GEN-END:variables
}
