/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.BorderLayout;
import volvis.RenderingController;

/**
 *
 * @author michel
 */
public class SurfaceTFPanel extends javax.swing.JPanel {

    private RenderingController renderController;
    private SurfaceTFEditor stfEditor;
    
    /**
     * Creates new form RaycastRendererPanel
     */
    public SurfaceTFPanel(RenderingController renderer) {
        initComponents();
        this.renderController = renderer;
        this.stfPanel.setLayout(new BorderLayout());
    }
    
    public void setSTFEditor(SurfaceTFEditor ed) {
        if (stfEditor != null) {
            stfPanel.remove(stfEditor);
        }
        stfEditor = ed;
        stfPanel.add(ed, BorderLayout.CENTER);
        stfPanel.repaint();
        repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stfPanel = new javax.swing.JPanel();

        javax.swing.GroupLayout stfPanelLayout = new javax.swing.GroupLayout(stfPanel);
        stfPanel.setLayout(stfPanelLayout);
        stfPanelLayout.setHorizontalGroup(
            stfPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 489, Short.MAX_VALUE)
        );
        stfPanelLayout.setVerticalGroup(
            stfPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 362, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(stfPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(stfPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel stfPanel;
    // End of variables declaration//GEN-END:variables
}
